name: Docker publish

on:
  workflow_call:
    inputs:
      repository:
        description: "Repository to checkout"
        required: false
        type: string
      build-args:
        description: "Docker build args"
        required: false
        type: string
      docker-image:
        description: "Name of the docker image to push"
        required: true
        type: string
      docker-platforms:
        description: "List of comma separated platforms to build"
        required: false
        type: string
        default: "linux/amd64"
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      docker-repo:
        description: "Docker registry to push to"
        required: true
      docker-username:
        description: "Docker username"
        required: true
      docker-token:
        description: "Docker token"
        required: true
    outputs:
      image-digest:
        description: "Pushed docker image's digest"
        value: ${{ jobs.publish.outputs.digest }}

jobs:
  publish:
    name: Docker - Publish
    runs-on: ["ubuntu-latest", "${{ inputs.runs-on }}"]
    concurrency: docker-${{ inputs.docker-tag }}
    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.7
        with:
          repository: '${{ inputs.repository }}'
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.6.1
      - name: Login on registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ${{ secrets.docker-repo }}
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-token }}
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.5.1
        with:
          images: ${{ secrets.docker-repo }}/${{ inputs.docker-image }}
          tags: |
            # Default values
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            # set latest tag for master branch
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', github.event.repository.default_branch) }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v6.6.1
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          platforms: ${{ inputs.docker-platforms }}
          build-args: |
            BUILDX_QEMU_ENV=true
            ${{ inputs.build-args }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
