name: Docker publish

on:
  workflow_call:
    inputs:
      docker-image:
        description: "Name of the docker image to push"
        required: true
        type: string
      docker-tag:
        description: "Tag of the docker image to push, defaults to current branch name"
        required: false
        type: string
        default: ""
    secrets:
      docker-repo:
        description: "Docker registry to push to"
        required: true
      docker-username:
        description: "Docker username"
        required: true
      docker-token:
        description: "Docker token"
        required: true
    outputs:
      image-digest:
        description: "Pushed docker image's digest"
        value: ${{ jobs.publish.outputs.digest }}

jobs:
  publish:
    name: Docker - Publish
    runs-on: ubuntu-latest
    concurrency: docker-${{ vars.docker-tag }}
    outputs:
      digest: ${{ steps.docker_build.outputs.digest }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2.9.1
      - name: Login on registry
        uses: docker/login-action@v2.2.0
        with:
          registry: ${{ secrets.docker-repo }}
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-token }}
      - name: Calculate image tag
        id: image-tag
        run: |
          if [ -z "${{ inputs.docker-tag }}" ]; then
            echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.docker-tag }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v4.1.1
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.docker-repo }}/${{ inputs.docker-image }}:${{ steps.image-tag.outputs.tag }}
          platforms: linux/amd64
          build-args: BUILDX_QEMU_ENV=true
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
