name: Gradle Minecraft build

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version to use"
        required: true
        type: string
      java-distribution:
        description: "JDK distribution to use"
        required: false
        type: string
        default: "temurin"
      runs-on:
        description: "Runner to use"
        required: false
        type: string
        default: "ubuntu-latest"
    secrets:
      keystore:
        required: false
      keystore-passphrase:
        required: false
      key-alias:
        required: true
      key-store-pass:
        required: true
      key-pass:
        required: true

permissions:
  contents: write

jobs:
  build:
    name: Gradle - Build
    runs-on: ["ubuntu-latest", "${{ inputs.runs-on }}"]
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1
      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Restore keystore
        run: |
          if [ ! -z "${{ secrets.keystore }}" ]; then
            echo "${{ secrets.keystore }}" > keystoreForgeMods.jks.asc
            gpg -d --passphrase "${{ secrets.keystore-passphrase }}" --batch keystoreForgeMods.jks.asc > keystoreForgeMods.jks
          fi

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3.3.1
      - name: Build
        run: |
          ./gradlew \
          build \
          -PforgeKeyStore=keystoreForgeMods.jks \
          -PforgeKeyStoreAlias=${{ secrets.key-alias }} \
          -PforgeKeyStorePass=${{ secrets.key-store-pass }} \
          -PforgeKeyStoreKeyPass=${{ secrets.key-pass }} \
          -PforgeSignSHA1=f927f4701bf4c0620c7bd0a501ce278f5e5ecc62

      - name: Upload mod file
        uses: actions/upload-artifact@v4.3.3
        with:
          name: mod-file
          path: |
            build/libs/*.jar
          if-no-files-found: error
          retention-days: 7
