name: Gradle Docker publish

on:
  workflow_call:
    inputs:
      java-version:
        description: "JDK version to use"
        required: true
        type: string
      java-distribution:
        description: "JDK distribution to use"
        required: false
        type: string
        default: "temurin"
      docker-image:
        description: "Name of the docker image to push"
        required: true
        type: string
      docker-tag:
        description: "Tag of the docker image to push, defaults to current branch name"
        required: false
        type: string
        default: ""
    secrets:
      docker-repo:
        description: "Docker registry to push to"
        required: true
      docker-username:
        description: "Docker username"
        required: true
      docker-token:
        description: "Docker token"
        required: true

jobs:
  publish:
    name: Gradle - Publish Docker
    runs-on: ubuntu-latest
    concurrency: docker-${{ vars.docker-tag }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v3
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: ${{ inputs.java-distribution }}
          java-version: ${{ inputs.java-version }}

      - name: Calculate image tag
        id: image-tag
        run: |
          if [ -z "${{ inputs.docker-tag }}" ]; then
            echo "tag=${GITHUB_REF##*/}" >> "$GITHUB_OUTPUT"
          else
            echo "tag=${{ inputs.docker-tag }}" >> "$GITHUB_OUTPUT"
          fi
      - name: Jib
        uses: gradle/gradle-build-action@v2.7.0
        with:
          cache-disabled: true
          arguments: |
            jib
            -Djib.to.auth.username=${{ secrets.docker-username }}
            -Djib.to.auth.password=${{ secrets.docker-token }}
            -Djib.to.image=${{ secrets.docker-repo }}/${{ inputs.docker-image }}:${{ steps.image-tag.outputs.tag }}
            -Djib.console=plain
